### ISSUE TITLE
Missing blocks/shares?

### ISSUE THREAD

**Issue by trgm7** [onemorebsmith/kaspa-stratum-bridge#7]
Hi,

I've noticed that there is missing jobs in the miner log compared to otter stratum adapters. This in turn is causing less blocks to be found. If you look in the pics I've attached, Ive compared it to kstratrum. The adapter seems to skip some blocks or not forward them to the miner?
![kasap-stratum-brdige](https://user-images.githubusercontent.com/111731472/186054987-b4cf7a9c-0e00-48ca-90a8-be6c7f905165.png)
![kstratum](https://user-images.githubusercontent.com/111731472/186054993-f99b2699-b27f-45bb-a03f-5f8f96895921.png)

**Comment by onemorebsmith** [comment]
Not sure what the issue is but it'll be a moot point. Next release moves to a constant diff, shares-based approach.

**Comment by onemorebsmith** [comment]
Should be resolved w/ the latest release. Closing

**Comment by trgm7** [comment]
After trying the new release, still facing the same problem. It actually seems worse now. Jobs are being received in 10+ second intervals
![Capture](https://user-images.githubusercontent.com/111731472/186169961-4b0bcbe6-0a40-402d-a355-52123d18d120.PNG)

**Comment by onemorebsmith** [comment]
Added some debug logging on my side, looks like I'm sending the updates but the block itself is only changing every ~20s or so. The timestamp in the image is from kaspad, when it changes the block has changed. 

![image](https://user-images.githubusercontent.com/59971111/186176121-29ea50c1-f2dd-43c3-a278-451479038b3e.png)

**Comment by onemorebsmith** [comment]
Switch to woolypooly to see the miner output, they do the same thing. It only reports a new job ever ~10s
![image](https://user-images.githubusercontent.com/59971111/186197332-e7c97d73-f069-4e5e-8610-5b3b773f2e8f.png)

**Comment by trgm7** [comment]
Ill give it ago, ill run both for over 24 hours as well

Do you think this is affecting anything?

**Comment by onemorebsmith** [comment]
I don't believe so. If I had to guess it's the miner choosing not to show the output for frequent jobs like that as to not spam the console. Interested to hear your results though! Appreciate it.

**Comment by onemorebsmith** [comment]
Any news on this?

**Comment by trgm7** [comment]
I had it running for the past 24 hours but had to restart it after roughly 12 hours. I'm not 100% sure but I have a feeling that after a certain period of time  blocks aren't being found on any of the miners, Shares are working OK. I have two instances running mining to two different wallet address' over the 24 hours they both mined the same amount of blocks (6 each), now I know for 1.3~gh that is very lucky , ill keep an eye on it over the next 48 hours and see how it behaves.
![Capture](https://user-images.githubusercontent.com/111731472/186782654-6bf79aa3-fd8f-418f-aa01-f38de9b7c27b.PNG)
![Capture2](https://user-images.githubusercontent.com/111731472/186782662-6d29e27b-1fa2-4ad7-ad37-71e0e952e8a0.PNG)
![Capture3](https://user-images.githubusercontent.com/111731472/186782824-3017429a-fb00-4c02-9e4b-cb4c4756ec55.PNG)
![Capture4](https://user-images.githubusercontent.com/111731472/186782836-c2787b61-a71f-43b5-ba05-28eb14370cc0.PNG)

**Comment by onemorebsmith** [comment]
3 blocks in 24 hours on 1.3GH/s is some crazy luck, nice! I've only been hitting around ~3 blocks/day with 3 GH/s.

Thanks for the update, really appreciate it. Let me know in a bit if you narrow down any issues or see any more weirdness.

**Comment by trgm7** [comment]
It has 6! Extremely lucky! I had to close and re-open the stratum after the first 12 hours. 3 blocks were found in the previous instance.
Also if it possible to mine to two address' in the same instance?
Will let you know how it goes, Thanks for your work!

**Comment by onemorebsmith** [comment]
Yep, if you're using the 1.0 release it'll use the address sent from the miner. You can actually just delete the mining address out of the config.yaml as it's not used any more.

**Comment by onemorebsmith** [comment]
Going to go ahead and close this. Reopen if you see issues
